name: Build and Deploy Spring boot - CAJA ICA

on:
  push:
    branches: [main]

jobs:
  build-docker:
    name: Build and deploy Spring Boot Api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build Spring with Maven
        run: mvn pom.xml clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Spring Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}:latest

  deploy:
    name: Deploy to DonWeb
    needs: build-docker
    runs-on: self-hosted #ubuntu-latest

    steps:
      - name: Docker Instance Stop and remove
        run: docker rm -f spring-api

      - name: Docker pull Spring image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/caja-ica:latest

      - name: Docker run Spring image
        run: |
          docker run -d \
          --restart always \
          --name spring-api \
          -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
          -e "DATASOURCE_URL=${{ secrets.DATASOURCE_URL }}" \
          -e DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
          -e DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
          -p 9896:9896 \
          ${{ secrets.DOCKERHUB_USERNAME }}/caja-ica:latest
